---
version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  nats:
    image: nats
    ports:
      - 4222:4222
  postgres:
    image: r3labs/postgres
    ports:
      - 5432:5432
    environment:
      DB_NAME: users,groups,datacenters,services
  nginx:
    image: nginx
    volumes:
      - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
    links:
      - api-gateway:api-gateway
      - monit:monit
    ports:
      - 80:80
