version: 2
jobs:
   build:
     machine:
       image: circleci/classic:201709-01
     working_directory: /home/circleci/.go_workspace/src/github.com/r3labs/composable
     steps:
       - checkout
       - run:
           name: Install Dependencies
           command: make dev-deps
       - run:
           name: Code Analysis
           command: make lint
       - run:
           name: Unit Tests
           command: make test
